dependencies:
- name: secrets-store-csi-driver
  #repository: https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts
  repository: https://github.com/alexanikiev/secrets-store-csi-driver/tree/master/charts
  version: 0.0.20
  condition: secrets-store-csi-driver.install
